repos:
- repo: local
  hooks:
    - id: lint
      name: Linting
      entry: poetry run poe lint
      language: system
      files: \.py$
- repo: local
  hooks:
    - id: format
      name: Formatting
      entry: poetry run poe format
      language: system
      files: \.py$
- repo: local
  hooks:
    - id: test
      name: Running unit tests
      entry: poetry run poe test
      language: system
      stages: [push]
- repo: local
  hooks:
    - id: typecheck
      name: Typechecking
      entry: poetry run poe typecheck
      language: system
      files: \.py$
