repos:
- repo: local
  hooks:
    - id: lint
      name: Linting
      entry: uv run poe lint
      language: system
      files: \.py$
- repo: local
  hooks:
    - id: format
      name: Formatting
      entry: uv run poe format
      language: system
      files: \.py$
- repo: local
  hooks:
    - id: typecheck
      name: Typechecking
      entry: uv run poe typecheck
      language: system
      files: \.py$
- repo: local
  hooks:
    - id: test
      name: Running unit tests
      entry: uv run poe test
      pass_filenames: false
      language: system
      stages: [pre-push]
