[tool.poetry]
name = "python-project-standard"
version = "0.1.0"
description = "A template for modern Python projects"
authors = ["jvilders <60934195+jvilders@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.1"
pandas = "^2.2.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.5"
pre-commit = "^3.7.1"
mypy = "^1.10.0"
pandas-stubs = "^2.2.2.240514"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
