name: "Project setup"
description: "This action checks out the commit, sets up Python and Poetry, then installs the project"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      shell: bash
      run: uv python install # Uses version from .python-version file

    - name: Run pre-install script
      shell: bash
      run: uv run python -m scripts.pre_install

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev
