name: Code checks

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
        description: "Whether the new version is a release. This determines whether the version is grabbed from the tag (release) or an alpha is made using the last published tag (PR)"

jobs:
  code-checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-action

      - name: Lint
        id: lint
        run: |
          uv run poe ci-lint

      - name: Format
        id: format
        run: |
          uv run poe ci-format

      - name: Typecheck
        id: typecheck
        run: |
          uv run poe ci-typecheck

      - name: Unit-test
        id: unit-test
        run: |
          uv run poe test

