name: Publish

on:
  workflow_call:
    inputs:
      package_version:
        required: true
        type: string
        description: "The version of the package to publish"
      release:
        required: true
        type: boolean
        description: "Whether the new version is a release. This determines whether the version is grabbed from the tag (release) or an alpha is made using the last published tag (PR)"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Verify package_version is non-empty
        run: |
          if [ -z "${{ inputs.package_version }}" ]; then
          echo "package_version input is empty, ensure this is correctly passed from the build step"
          exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-action

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist

      - name: Publish
        id: publish
        run: |
          uv run poe publish
