name: Publish

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-action

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist

      - name: Publish
        id: publish
        run: |
          uv run poe publish
