name: Pull request workflow
on:
  pull_request:
    branches: [main]

jobs:
  code-checks:
    uses: ./.github/workflows/code-checks.yml
    with:
      release: false

  build:
    uses: ./.github/workflows/build.yml
    needs: code-checks
    with:
      release: false

  publish:
    uses: ./.github/workflows/publish.yml
    needs: build
    with:
      package_version: ${{ needs.build.outputs.package_version }}
      release: false